apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: mysql-claim 
  namespace: citizen
spec:
  accessModes:
    - ReadWriteOnce 
  volumeMode: Filesystem 
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi